### ISSUE TITLE
item.Expiration.Second undefined

### ISSUE THREAD

**Issue by eicca** [ulule/limiter#10]
After trying to `go get` the project I got the following:
```
# github.com/ulule/limiter
../../ulule/limiter/store_memory.go:70: item.Expiration.Second undefined (type int64 has no field or method Second)
```

Looks like `go-cache` dependency was changed in a non-compatible way. I noticed that somebody already fixed this problem in the fork: https://github.com/jimpeak/limiter/commit/218c2c9f90c9fc9db229ed6cf516631ae00ada64

If the change makes sense, would it be possible to merge it? Thanks.

**Comment by thoas** [comment]
done, thank you
