### ISSUE TITLE
For gin as middleware: any solution to limit only specific route, or only successful request?

### ISSUE THREAD

**Issue by hyorigo** [ulule/limiter#118]
Hi guys, do you have any solutions to limit only specific route, or only successful request for Gin?

**Comment by novln** [comment]
Hello @hyorigo,

I would suggest to create your own Gin middleware and copy the implementation of `Handle(c *gin.Context)` defined here:
https://github.com/ulule/limiter/blob/cbdad0eedb171f94bf0b06fbc01f391ff704e88c/drivers/middleware/gin/middleware.go#L40

Then, you could execute the limiter whenever you want.

Hope that's help.

Cheers,

**Comment by novln** [comment]
Closing since there is no update on this issue.
