### ISSUE TITLE
Change limiter rate on the fly

### ISSUE THREAD

**Issue by aksh-gupta** [ulule/limiter#122]
Can we change the period and limit on the fly?

I have the limit and period stored in DB and want to change it in DB and it should reflect as a new period and limit.

**Comment by aksh-gupta** [comment]
I changed the limiter instance's Rate in the `KeyGetter` function and that allowed to change rate in realtime.

**Comment by novln** [comment]
There is also this solution: https://github.com/ulule/limiter-examples/issues/4#issuecomment-721138372

Glad you find a solution.
