### ISSUE TITLE
Is there any way to skip rate limit and keep service available even store crashed?

### ISSUE THREAD

**Issue by zacfeng** [ulule/limiter#128]
I've found the Handle function will always do `c.Abort()` even go cache or redis server crashed.
Just want to keep service available when store disconnected. 
Is it possible to move gin context abort to the default handler? So we can customize our ErrorHandler for our needs. 

```golang
func (middleware *Middleware) Handle(c *gin.Context) {
	key := middleware.KeyGetter(c)
	if middleware.ExcludedKey != nil && middleware.ExcludedKey(key) {
		c.Next()
		return
	}

	context, err := middleware.Limiter.Get(c, key)
	if err != nil {
		middleware.OnError(c, err)
		c.Abort()
		return
	}
}

**Comment by novln** [comment]
Hello :wave: 

Simply copy the middleware in your codebase, change it with the desired behavior and use this last one with gin.

Cheers,

**Comment by zacfeng** [comment]
Hi Novln, thanks for your suggestion. It's a low-cost solution.
Also, I've read the objective limiter v4, remove panic() in ErrorHandler is a good idea.
Thanks for building the great middleware! That does help!
