### ISSUE TITLE
work behind load balancer

### ISSUE THREAD

**Issue by gzhhong** [ulule/limiter#168]
Hello, 

I will deploy my service behind a load balancer, means all of the request from users will send firstly to the load balancer, then the LB will forward the request to my service. In such architecture, it is said by https://aws.amazon.com/premiumsupport/knowledge-center/elb-find-load-balancer-IP/ that '''You can determine the IP addresses associated with an internal load balancer or an internet-facing load balancer by resolving the DNS name of the load balancer. These are the IP addresses where the clients should send the requests that are destined for the load balancer. However, Classic Load Balancers and Application Load Balancers use the private IP addresses associated with their elastic network interfaces as the source IP address for requests forwarded to your web servers.''' In such architecture, if the source IP of the request is the IP of the load balancer (not the IP of the end user), if ulule apply the request rate limitation, it will in fact limit the total output of the service. Should I do some configuration on ulule limiter or the on the load balancer? or ulule already support such architecture quite well? 

Thanks for your answer,

James

**Comment by novln** [comment]
Hello,

You should use https://github.com/ulule/limiter/blob/master/options.go#L17

**Comment by gzhhong** [comment]
@novln , Thanks a lot for the information. Yes, you can close the issue. Thanks.

**Comment by novln** [comment]
Perfect :+1:
