### ISSUE TITLE
Should be flexible enough to support advanced use-cases

### ISSUE THREAD

**Issue by Harry-027** [ulule/limiter#170]
We were considering this library to be used for advanced use-cases such as limiting requests based on Graphql query complexity. I see this works great with RPS use-case but it can also support other use-cases if library consumers are allowed to pass an integer value (a variable instead of hard-coded value `1`) to increment method available under drivers (redis/memory) ( [Inc method](https://github.com/ulule/limiter/blob/master/drivers/store/redis/store.go#L102) ). This way it would be more flexible for user to pass any value to Redis `incrby` script as per their needs. I think it would be practical to add another method or api to allow this so to extend it for other use cases as well.

**Comment by Harry-027** [comment]
Thanks @novln ! 

I have raised a PR to support this (added one more method under drivers instead to support the use case). Hopefully it won't break compatibility as this would be a different method altogether. Skipping its usage under middlewares for now (keeping it   flexible for first iteration as users might want to execute it on a different layer) & could be added later. Would appreciate if you could review the PR and give some feedback. Thanks!

**Comment by novln** [comment]
@Harry-027 Should we close this issue ?

**Comment by Harry-027** [comment]
> @Harry-027 Should we close this issue ?

Sure @novln ! Thanks for the release 🚀
