### ISSUE TITLE
Per-route limiting

### ISSUE THREAD

**Issue by mrusme** [ulule/limiter#175]
I discovered this project while looking for a way to limit requests **per route** (not necessarily per IP). Example:

On a route like `/document/361e556c-66f1-4f40-aeff-5cde5d00597b` it would be nice to be able to specify a limit for GET/POST/PATCH requests per minute, using the variable (in this case the UUID at the end) as key in redis. This way, each *document* could be rate limited individually.

Before even trying to implement this, I was wondering if this (partially different) approach would be something the maintainer(s) here would be interested in incorporating into this library? If so I could try to extend the library and incorporate this as an optional feature. If that's not of interest I'd most likely fork and modify the lib so that it does what I'm looking for.

**Comment by novln** [comment]
Hello,

Even if the issue is old, you could take a look here: https://github.com/ulule/limiter/issues/44

Or, assuming you use gin middleware, you could use `WithKeyGetter`.
https://github.com/ulule/limiter/blob/master/drivers/middleware/gin/options.go#L54

Cheers,

**Comment by mrusme** [comment]
Oh, I overlooked `WithKeyGetter`, indeed this looks like it could work for what I'm doing. Thank you! I will try this first and re-open in case it doesn't solve the issue.
