### ISSUE TITLE
Reintroduce Ping function to the Client interface

### ISSUE THREAD

**Issue by rcjsuen** [ulule/limiter#177]
What was the reasoning behind removing it in #120? Can it be added back?

**Comment by novln** [comment]
@yansal I think this is a question for you.

I'm okay to add it back.

**Comment by yansal** [comment]
The reasoning is that it's simpler if this library does not ping redis. We use redis for many different things and when we create a new redis client we always ping redis before instantiating the limiter/cache/lock/datastore client. This library was the only one doing an additional ping, so removing the ping made it more consistent with many other open source libraries using redis.

**Comment by thoas** [comment]
no need to add it back, you can simply ping yourself with the redis client before creating the limiter store.
