### ISSUE TITLE
Rate limiting based on custom identity

### ISSUE THREAD

**Issue by batara666** [ulule/limiter#189]
How can I rate-limit based on custom identity like a variable that loaded from database and not an IP Address

The rate limit are also difference between each identity

My framework are Gin, It is possible to do this with this library?

**Comment by ns-kliu** [comment]
I believe this can help
https://github.com/ulule/limiter/blob/1324de5543eef04ae164c331ff42bcd92c625f5f/drivers/middleware/gin/options.go#L51

**Comment by novln** [comment]
@ns-kliu Thank you for your answer, that's correct.
I'm closing this issue.
