### ISSUE TITLE
About algorithms

### ISSUE THREAD

**Issue by sytungan** [ulule/limiter#237]
Hi,
I am interested in using the ulule/limiter library to rate limit requests in my application. I am wondering which algorithm you chose to use (e.g., leaky bucket or token bucket).

Thank you for your time.

**Comment by novln** [comment]
Hello,

You can find the answer of this issue #204

If you have further questions, don't hesitate :slightly_smiling_face:

**Comment by sytungan** [comment]
Thank for your reply!
