### ISSUE TITLE
Consider changing the in memory cache library

### ISSUE THREAD

**Issue by stonymahony** [ulule/limiter#238]
The library [go-cache](https://github.com/patrickmn/go-cache) used (or a fork thereof, according to your documentation) seems solid, but not particularly actively maintained. The last release is from 2017.

In the meantime, there are other mature, more actively maintained and possibly better performing caching libraries, e.g. [bigcache](https://github.com/allegro/bigcache) or [freecache](https://github.com/coocood/freecache).

Are you considering switching to one of them or are you happy with the status quo?

**Comment by thoas** [comment]
Hi, we don't provide additional features than what we need internally, so if you want a particular driver go send a PR, we will review it.
