### ISSUE TITLE
Add ruedis support

### ISSUE THREAD

**Issue by rusdevops** [ulule/limiter#247]
[go ruedis](https://github.com/redis/rueidis) has [go-redis-like-api-adapter](https://github.com/redis/rueidis/tree/main/rueidiscompat#go-redis-like-api-adapter)

currently, a compilation error occurs when trying to use the adapter

1. need to change signatures of [Client interface](https://github.com/ulule/limiter/blob/4cb9c1da463323082c729a1ebc90df7dc9e76b48/drivers/store/redis/store.go#L45-L51)
- `StringCmd` 
- `StatusCmd`
- `BoolCmd`
- `IntCmd`
- `Cmd`

for example add corresponding interfaces `StringCmd`, ...

2. or add new driver ruedis

**Comment by thoas** [comment]
Hi, we don't provide additional features than what we need internally, so if you want a particular driver go send a PR, we will review it.

**Comment by rusdevops** [comment]
Create PR: https://github.com/ulule/limiter/pull/248
