### ISSUE TITLE
package limiter/drivers/store/common includes test flags in main binary

### ISSUE THREAD

**Issue by justinfx** [ulule/limiter#34]
I'm currently using "limiter/drivers/store/memory" cache independently from also using the `Limiter`. It seems that because there is a "limiter/drivers/store/common/tests.go" in the `common` package, the `testing` package injects its flags into my application.

Could this tests.go file be renamed to "common_test.go"?

**Comment by novln** [comment]
Hello,

Yeah that's kind of annoying, let me think of a solution...
Because renaming the file to `common_test.go` won't solve the problem _(I think I've already tried that)_.

**Comment by justinfx** [comment]
Why would renaming it not solve the problem? That is what I had to do locally. Or maybe I am missing something since I didn't try running the tests.

**Comment by novln** [comment]
Yep, renaming it `common_test` won't expose `TestStoreSequentialAccess` and `TestStoreConcurrentAccess` to `memory` and `redis` testing subpackage.

I'm currently working on a okayish workaround.

**Comment by novln** [comment]
@justinfx It should be ok now :smiley:

**Comment by justinfx** [comment]
Thanks!
