### ISSUE TITLE
Dep hell

### ISSUE THREAD

**Issue by retNull** [ulule/limiter#35]
I'm fairly new to Go and I love it except for the dependency management. Maybe you have some experience with this:

Gin hasn't had a release since July 2017 but they are always updating the master branch with great features.  In my project, I'm using "branch=master" and you are using "version=1.2" in Gopkg.toml.  Do you know any tricks to make importing your project work with the gin's mismatching dependency versions?  I would like to stay on the master branch of gin while using your wonderful library.

Thanks

**Comment by novln** [comment]
> I'm fairly new to Go and I love it except for the dependency management. 
Yep that's a pain in the ...

> Gin hasn't had a release since [...] I would like to stay on the master branch of gin while using your wonderful library.

Have you tried the `[[override]]` directive in your `Gopkg.toml` ? It should ignore our version and use the one you specify.

**Comment by retNull** [comment]
You are a life saver. For some reason, my google research never came up with that solution.  Thanks!
