### ISSUE TITLE
Rate Limiting certain methods on a Thrift endpoint

### ISSUE THREAD

**Issue by sagard** [ulule/limiter#38]
I think its more of a question but was not sure what is the right place to ask this.

I am using thrift with HTTP middleware. Our clients call us using Thrift JSON.

Here is a sample call to the login endpoint:
```
URL : /auth
Body:
{
  "method" : "login",
  "arguments": {
    "email": "",
    "password": "<PASSWORD>"
  }
```

I can rate limit the entire /auth endpoint. Is there a way I can rate limit certain methods on the endpoint?

**Comment by novln** [comment]
I can think of two method, from what I prefer to a more "hackish" but correct solution.

The first one is to can chain the limiter middleware on specific endpoint, if you have a mux router like `chi` or `gin`. Like for example:

```go
r.Route("/auth", func(r chi.Router) {
    r.Use(limiter)
    ...
}
```

Or you can either add a condition here (https://github.com/ulule/limiter/blob/master/drivers/middleware/stdlib/middleware.go#L34) to ignore specific endpoint using `*http.Request`.

Do not hesitate if you have further questions.

**Comment by sagard** [comment]
Thanks, novin .  I followed your 2nd solution.
I created an overridden Hander method in my file and ignored endpoints by checking the request.

**Comment by novln** [comment]
Perfect :smile: 
Don't hesitate to close if you don't have further questions.
