### ISSUE TITLE
patch release for redis pttl bug fix

### ISSUE THREAD

**Issue by andrewhoff** [ulule/limiter#48]
Hey! just noticed that a patch release was never cut for https://github.com/ulule/limiter/pull/45 and https://github.com/ulule/limiter/pull/46 combined, wondering if that will be something we can expect soon? Or that maybe isn't necessary as people can just constrain to `master`...

Thanks!

**Comment by novln** [comment]
Hello,

A minor memory lapse _(don't know if it's the english terms)_, I'm doing this right now.

**Comment by andrewhoff** [comment]
Thanks @novln! Appreciate it!
