### ISSUE TITLE
v3.0.0 tag?

### ISSUE THREAD

**Issue by paride** [ulule/limiter#49]
Does the v3.0.0 tag actually point to the latest stable release? It seems to point to a commit in a development branch...

**Comment by novln** [comment]
Hello,

The `v3.0.0` is still in development because we are waiting some feedback from go modules ecosystem/community in order to not break compatibility with `dep` _(we hope)_.

Cheers,

**Comment by novln** [comment]
You can find the pull request here: https://github.com/ulule/limiter/pull/39
