### ISSUE TITLE
Add Feature to control Redis Storing

### ISSUE THREAD

**Issue by imjuanleonard** [ulule/limiter#54]
Right now it is storing the redis key based on client IP.
Can we modify this to something, let say header or client ID.

Storing only API's is unusable where the use cases is to limit based on request or client

**Comment by novln** [comment]
Hello,

Please take a look at the response on this issue: https://github.com/ulule/limiter/issues/44

If you have any question, don't hesitate to ask :slightly_smiling_face:

**Comment by imjuanleonard** [comment]
Thanks, closing this
