### ISSUE TITLE
Go mod & v3

### ISSUE THREAD

**Issue by Manawasp** [ulule/limiter#55]
Hello,

I'm new to `go mod` and i'm adding it to a project :
Currently with a go mod init I got this version of the limiter :
- `github.com/ulule/limiter v2.2.2+incompatible`

I tried to force ugrade to v3 but I got an error :
```
$ go get github.com/ulule/limiter@v3.1.0
go: finding github.com/ulule/limiter v3.1.0
go: github.com/ulule/limiter@v0.0.0-20190117112858-4a9155baecad: go.mod has post-v0 module path "github.com/ulule/limiter/v3" at revision 4a9155baecad
go: error loading module requirements
```

I see this PR https://github.com/ulule/limiter/pull/39 and look like supported.
Do you have an idea ?

Thanks !

**Comment by novln** [comment]
Sorry, I should update the README it's not correct 😕

To use `go mod` with `github.com/ulule/limiter`, you should use this command:

`go get github.com/ulule/limiter/v3@v3.1.0`

If you have any question, don't hesitate 🙂

**Comment by Manawasp** [comment]
It works perfectly thank you :+1:
