### ISSUE TITLE
Memory store clean command is a blocker

### ISSUE THREAD

**Issue by gadelkareem** [ulule/limiter#86]
Limiter is running on a high traffic server so while debugging some problems I saw high letancy from the store cleaner. I know that we need to remove the expired records but maybe there is a better way to do it?

![Screenshot 2020-03-27 at 8 07 56 PM](https://user-images.githubusercontent.com/1441127/77802162-9668e800-707a-11ea-8f3b-33615046bd46.png)

**Comment by novln** [comment]
Hello,

Do you have any suggestions by any chances ?
Also, if you tried using redis store ? The in-memory store was more or less designed for debug and/or development.

Cheers,

**Comment by novln** [comment]
Could I have an example of your expiration duration ?

**Comment by gadelkareem** [comment]
> Hello,
> 
> Do you have any suggestions by any chances ?
> Also, have you tried using redis store ? The in-memory store was more or less designed for debug and/or development.
> 
> Cheers,

I think redis store would remove the the bottleneck since there is no cleaner on the app but for a single deployment it would create unneeded latency. 
For the in-memroy the deletion of expired records could be done like this https://github.com/gadelkareem/cachita/blob/master/memory.go#L82 because of this issue https://github.com/golang/go/issues/20135 but that would not be the best solution yet since cleaner will block again. I am not sure how to tackle the in-memory cleaner but maybe if there is a replica of the counters hash map that is used only for reading and the writing could be done through channels in go routines. But I am not sure how to do increment in this way.

> Could I have an example of your expiration duration ?
```
r.generalLimiter = newLimiter("4-S")
r.apiLimiter = newLimiter("50-M")
r.searchLimiter = newLimiter("30-M")
func newLimiter(rate string) *limiter.Limiter {
    r, err := limiter.NewRateFromFormatted(rate)
    h.PanicOnError(err)
    return limiter.New(memory.NewStore(), r, limiter.WithTrustForwardHeader(true))
}
```

**Comment by novln** [comment]
I may have a solution using a ring buffer, would you like to experiment it ?

**Comment by gadelkareem** [comment]
Sure!

**Comment by novln** [comment]
@gadelkareem Could I have an example on how many keys you have in your store, so I could have a good telemetry on how my idea improve (or not) things ?!

Thank you.

**Comment by gadelkareem** [comment]
@novln I am afraid that would be hard to calculate because it is production data but we can estimate it through the number of requests which is around 1.2 Million request per day.

**Comment by novln** [comment]
Hello,

Could you try this commit 3cd0e5aa35fd10f3288b53d95f12431a50515a63?

I haven't done a benchmark nor a ring buffer in order to try to keep the initial architecture.
Also, it was quicker to try this and find a quick and good enough solution for your problem.

**Comment by gadelkareem** [comment]
I tested it with stack impact and I do not see that blocker anymore but i made a PR so you can test it more intensely.
