### ISSUE TITLE
stateless solution - but how to accomplish for non-logged in users

### ISSUE THREAD

**Issue by ORESoftware** [ulule/limiter#87]
We can throttle logged-in users in our application code by inspecting the JWT and looking at how many requests they made in the last minute etc.  AKA, we decrypt the JWT, add the current request timestamp to a queue property, and see how many requests there were in the tiny queue in the JWT.

So that works for non-logged in users without using Redis etc.
But is there a good methodology to throttle non-logged in users? By IP address or something else?
I don't think using an external data store for every request is optimal in terms of performance or simplicity.

I posted a similar question on SO for reference:
https://stackoverflow.com/questions/60958202/how-to-throttle-non-logged-in-users

**Comment by novln** [comment]
Hello,

Yeah, you could throttle by IP address, even though with IPv6 you'll have to use a mask.
Keep it simple.
