### ISSUE TITLE
unclear how to rate limit by IP address

### ISSUE THREAD

**Issue by ORESoftware** [ulule/limiter#88]
from the docs (at least the readme file), it's unclear how to rate limit by IP address, if this is a goal of the library.

**Comment by ORESoftware** [comment]
alright, I just did a ctrl-f for "IP" and low and behold IP addresses are the basis for the lib. that's good news. however, it's not all that clear - why not just copy some of the code from the library to the readme that handles the IP and that way show potential users how it works? that's my request :)

**Comment by novln** [comment]
Hello :slightly_smiling_face: 

It's written on the README: 

> **Usage:**
> In five steps:
> * Create a limiter.Rate instance (the number of requests per period)
> * Create a limiter.Store instance (see Redis or In-Memory)
> * Create a limiter.Limiter instance that takes store and rate instances as arguments
> * Create a middleware instance using the middleware of your choice
> * Give the limiter instance to your middleware initializer

You also have multiple examples of working implementation with different middleware.

But I take your point, I'll add a middleware example in the code block.

**Comment by ORESoftware** [comment]
thanks!
