### ISSUE TITLE
address common concern of multi-node clusters

### ISSUE THREAD

**Issue by ORESoftware** [ulule/limiter#89]
Most production users will be using multiple golang servers in a cluster like Kubernetes or Mesos.  If we rate limit by IP in each individual node it's possible by chance, even with a round robin strategy, that a certain node will get hit by the same IP and get unfairly limited.  or the reverse, hit all the node's in the cluster evenly and then slip through.

Perhaps add a caveat that rate limiting by IP should probably be done by load balancers when working with clusters?

**Comment by thoas** [comment]
If you are working with a cluster, you need a centralised storage (redis, etc.), in-memory cannot be used.
