### ISSUE TITLE
setRate function refresh the key expire time when the key exist?

### ISSUE THREAD

**Issue by jinhao** [ulule/limiter#9]
hi, 
 i have a question, this function below in store_redis.go
```golang
  func (s RedisStore) setRate(c redis.Conn, key string, rate Rate) ([]int, error) {
        c.Send("MULTI")
        c.Send("SETNX", key, 1)
        c.Send("EXPIRE", key, rate.Period.Seconds())
        return redis.Ints(c.Do("EXEC"))
 }
```
if the key exist in redis, the function will refresh the expire time of the key, it's design so or bug?

**Comment by gillesfabio** [comment]
Hi @jinhao,

Thanks for your interest.

This function uses [SETNX](http://redis.io/commands/setnx). When key already holds a value, no operation is performed. 

So, this function should not refresh the expire time of the key.

**Comment by jinhao** [comment]
@gillesfabio 
> redis 127.0.0.1:6379> get a
"18"
redis 127.0.0.1:6379> ttl a
(integer) 907
redis 127.0.0.1:6379> watch a
OK
redis 127.0.0.1:6379> MULTI
OK
redis 127.0.0.1:6379> setnx a 1000
QUEUED
redis 127.0.0.1:6379> expire a 1000
QUEUED
redis 127.0.0.1:6379> EXEC
1) (integer) 0
2) (integer) 1
redis 127.0.0.1:6379> ttl a
(integer) 995

this is my test result, .is it any problem? my redis version is 2.6.14

**Comment by jinhao** [comment]
@gillesfabio  
I test it, and add print ttl every request
```goalng
131     if count < rate.Limit {
132         remaining = rate.Limit - count
133     }
134
135     log.Printf("count:%d ttl:%d remaining:%d\n", count, ttl, remaining)
```
the result:
> ➜  http git:(master) ✗ go run main.go
Server is running on port 6379...
2015/10/27 19:03:28 count:2 ttl:60 remaining:2
2015/10/27 19:03:28 count:3 ttl:60 remaining:1
2015/10/27 19:03:30 count:4 ttl:60 remaining:0
2015/10/27 19:03:31 count:5 ttl:60 remaining:0
2015/10/27 19:03:31 count:6 ttl:60 remaining:0
2015/10/27 19:03:33 count:7 ttl:60 remaining:0
2015/10/27 19:03:34 count:8 ttl:60 remaining:0
2015/10/27 19:03:34 count:9 ttl:60 remaining:0
2015/10/27 19:03:36 count:10 ttl:60 remaining:0
2015/10/27 19:03:36 count:11 ttl:60 remaining:0
2015/10/27 19:03:36 count:12 ttl:60 remaining:0
2015/10/27 19:03:38 count:13 ttl:60 remaining:0
2015/10/27 19:03:38 count:14 ttl:60 remaining:0
2015/10/27 19:03:38 count:15 ttl:60 remaining:0
2015/10/27 19:03:49 count:16 ttl:60 remaining:0
2015/10/27 19:03:49 count:17 ttl:60 remaining:0
2015/10/27 19:03:49 count:18 ttl:60 remaining:0

**Comment by gillesfabio** [comment]
:+1: Argh. Yes. `SETNX` only works with value.

Fixed here: https://github.com/ulule/limiter/commit/8ba0f24f149c7d161d98d2df15dc9f33e1d94963

Tell me if it works for you. I tried with a `time.Sleep()` and it properly sets TTL.

Thanks @jinhao.

**Comment by jinhao** [comment]
ok, it works! Thanks.
